# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'LoopbackSwiftCodeGenExample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  project 'LoopbackSwiftCodeGenExample'

  # Pods for LoopbackSwiftCodeGenExample
    pod 'Alamofire'    
    pod 'SwiftyJSON'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.1'
      if config.name == 'Debug'
          config.build_settings['OTHER_SWIFT_FLAGS'] = '-DDEBUG'
          else
          config.build_settings['OTHER_SWIFT_FLAGS'] = '-DRELEASE'
      end
    end
  end
end


  target 'LoopbackSwiftCodeGenExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoopbackSwiftCodeGenExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
